resolution: 448
num_generated_frames_per_clip: 18
fps: 19
num_init_past_frames: 16
num_past_frames: 20
inference_steps: 14
cfg_scale: 3
weight_dtype: bf16
enable_xformers_memory_efficient_attention: true

model_name_or_path: memoavatar/memo
# model_name_or_path: checkpoints
vae: stabilityai/sd-vae-ft-mse
wav2vec: facebook/wav2vec2-base-960h
emotion2vec: iic/emotion2vec_plus_large
misc_model_dir: checkpoints
